total_quotes = 629

anime_list = [
"3-gatsu no Lion",
"5 Centimeters Per Second",
"A Place Further Than The Universe",
"Akame Ga Kill",
"Angel Beats!",
"Assassination Classroom",
"Attack on Titan",
"Avatar",
"Barakamon",
"Beyond the Boundary",
"Black Clover",
"Blue Exorcist",
"Boruto",
"Clannad",
"Code Geass",
"Coyboy Bebop",
"Death Note",
"Death Parade",
"Demon Slayer",
"Detective Conan",
"Devilman Crybaby",
"Dr. Stone",
"Dragon Ball",
"Durarara",
"Erased",
"Fairy Tail",
"Fate Series",
"Fire Force",
"Food Wars!",
"Fullmetal Alchemist",
"Gate",
"Gintama",
"Gurren Lagann",
"Haikyuu!!",
"K",
"Kakegurui",
"Kill la Kill",
"Kuroko's Basketball",
"Mirai Nikki",
"Mob Psycho 100",
"Monster",
"Mushishi",
"My Hero Academia",
"Naruto",
"Nisekoi",
"No Game No Life",
"Noragami",
"One Piece",
"One Punch Man",
"Overlord",
"Owari no Seraph",
"Parastye",
"Plastic Memories",
"Re:zero",
"Seven Deadly Sins",
"Steins;gate",
"Sword Art Online",
"The Garden of Words",
"The Promised Neverland",
"The Rising of the Shield Hero",
"Tokyo Ghoul",
"Violet Evergarden",
"Weathering with You",
"Your Lie in April",
"Your Name"
]
